services:
  app:
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
          - "8000:8080"
      volumes:
          - .:/var/www/html
      depends_on:
          -   db
      environment:
          AUTORUN_ENABLED: "false"

  db:
      image: postgres:17
      ports:
        - "5433:5432"
      environment:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
          -   dbdata:/var/lib/postgresql/data
volumes:
    dbdata:
